import { getHfAuthHeaders } from './config.mjs';

const HF_API='https://huggingface.co/api/models';
const UA='FlexLab/0.4.4 (+local-ai-desktop)';
function lowerList(v){return(Array.isArray(v)?v:[]).map(x=>String(x).toLowerCase());}
function inferKind(raw){const p=String(raw.pipeline_tag||'').toLowerCase();const tags=lowerList(raw.tags);if(['text-to-image','image-to-image'].includes(p)||tags.some(t=>/text-to-image|stable-diffusion|diffusers|flux|qwen-image|mage-flow|ideogram|z-image/.test(t)))return'image';if(['text-to-audio','audio-to-audio','text-to-speech'].includes(p)||tags.some(t=>/musicgen|audiogen|bark|text-to-audio|audio-generation/.test(t)))return'music';return'llm';}
function inferThink(id,tags){const s=`${id} ${tags.join(' ')}`.toLowerCase();return/reasoning|thinking|deepseek-r1|gpt-oss|qwen3|seed-oss|stepfun/.test(s);}
function inferThinkLevels(id,tags){return/gpt-oss|seed-oss|reasoning-effort/.test(`${id} ${tags.join(' ')}`.toLowerCase());}
function inferVision(raw){const s=`${raw.id} ${raw.pipeline_tag||''} ${(raw.tags||[]).join(' ')}`.toLowerCase();return/image-text-to-text|vision|multimodal|vlm|qwen.*vl|gemma.*vision|llava|minicpm-v|pixtral/.test(s)||(raw.siblings||[]).some(f=>/mmproj/i.test(f.rfilename||''));}
function paramsFrom(id,tags){const m=`${id} ${tags.join(' ')}`.match(/(?:^|[-_\s])(\d+(?:\.\d+)?)\s*([bm])(?:[-_\s]|$)/i);return m?`${m[1]}${m[2].toUpperCase()}`:'';}
function contextFrom(raw){const hit=(raw.tags||[]).find(t=>/^\d+(?:k|m)$/i.test(String(t)));return hit?String(hit).toUpperCase():undefined;}
function fileSize(f){return Number(f.size||f.lfs?.size||0);}
function quantName(filename){const u=filename.toUpperCase();const m=u.match(/(IQ\d(?:_[A-Z0-9]+)*|Q\d(?:_[A-Z0-9]+)+|Q\d_\d|Q\d_K_[A-Z]|Q\d_K|Q\d)/);return m?.[1]||filename.split('/').pop();}
function chooseMmproj(siblings){return(siblings||[]).filter(x=>/mmproj.*\.(gguf|bin)$/i.test(x.rfilename||'')).map(x=>({file:x.rfilename,sizeBytes:fileSize(x)}));}
function ggufQuants(siblings){const files=(siblings||[]).filter(f=>/\.gguf$/i.test(f.rfilename||'')&&!/mmproj/i.test(f.rfilename||''));return files.map(f=>({id:quantName(f.rfilename),label:quantName(f.rfilename),sizeBytes:fileSize(f),file:f.rfilename})).sort((a,b)=>(a.sizeBytes||Number.MAX_SAFE_INTEGER)-(b.sizeBytes||Number.MAX_SAFE_INTEGER)).map((q,i,all)=>({...q,recommended:/Q4_K_M|Q4_K_S|Q5_K_M/i.test(q.label)?!all.slice(0,i).some(x=>/Q4_K_M|Q4_K_S|Q5_K_M/i.test(x.label)):false}));}
function snapshotQuant(siblings,label='Hugging Face snapshot'){return[{id:'snapshot',label,sizeBytes:(siblings||[]).reduce((n,f)=>n+fileSize(f),0),file:'*',recommended:true}];}
function simpleImageQuants(siblings){return(siblings||[]).filter(f=>/\.(safetensors|gguf|ckpt)$/i.test(f.rfilename||'')&&!/vae|text_encoder|clip|t5|lora|controlnet|mmproj/i.test(f.rfilename||'')).map((f,i)=>({id:f.rfilename,label:f.rfilename.split('/').pop(),sizeBytes:fileSize(f),file:f.rfilename,recommended:i===0}));}
function modernImageQuants(siblings){
  const all=(siblings||[]);const candidates=all.filter(f=>{const n=String(f.rfilename||'');return /\.(gguf|safetensors|ckpt)$/i.test(n)&&!/(?:vae|text_encoder|text_encoders|clip|t5|lora|controlnet|mmproj|uncond)/i.test(n)&&/(?:\/diffusion_models\/|\/transformer\/|\/unet\/|flux|qwen.?image|mage.?flow|ideogram|sd3|z.?image)/i.test(n);});
  const hasShards=candidates.some(f=>/-\d{5}-of-\d{5}\.safetensors$/i.test(String(f.rfilename||'')))||all.some(f=>/\.safetensors\.index\.json$/i.test(String(f.rfilename||'')));
  if(hasShards||!candidates.length)return snapshotQuant(siblings,'Pipeline snapshot');
  const rows=candidates.map(f=>({id:quantName(f.rfilename),label:quantName(f.rfilename),sizeBytes:fileSize(f),file:f.rfilename})).sort((a,b)=>(a.sizeBytes||Number.MAX_SAFE_INTEGER)-(b.sizeBytes||Number.MAX_SAFE_INTEGER));
  const preferred=rows.find(x=>/Q4_K_M|Q4_K_S|Q5_K_M/i.test(x.label))||rows[0];return rows.map(x=>({...x,recommended:x===preferred}));
}
function descriptor(raw){return`${raw.id} ${(raw.tags||[]).join(' ')} ${raw.pipeline_tag||''}`.toLowerCase();}
function pipelineHint(raw){const s=descriptor(raw);if(/qwen[-_ ]?image/.test(s))return'qwen-image';if(/mage[-_ ]?flow/.test(s))return'mage-flow';if(/flux.?2/.test(s))return'flux2';if(/flux/.test(s))return'flux1';if(/ideogram.?4/.test(s))return'ideogram4';if(/sd3|stable-diffusion-3/.test(s))return'sd3';if(/z-image/.test(s))return'z-image';if(/stable-diffusion|sdxl|sd1.?5/.test(s))return'sd';return'diffusers';}
export function mapHf(raw,source='huggingface',lmStudio={}){
  const kind=inferKind(raw),tags=raw.tags||[],vision=Boolean(lmStudio.vision??inferVision(raw)),think=Boolean(lmStudio.think??inferThink(raw.id,tags)),thinkLevels=Boolean(lmStudio.thinkLevels??inferThinkLevels(raw.id,tags));const mmproj=chooseMmproj(raw.siblings);const hint=pipelineHint(raw);
  let quants;if(kind==='llm'){quants=ggufQuants(raw.siblings);if(!quants.length)quants=snapshotQuant(raw.siblings,'Model snapshot');}else if(kind==='image')quants=hint==='sd'||hint==='diffusers'?simpleImageQuants(raw.siblings):modernImageQuants(raw.siblings);else quants=snapshotQuant(raw.siblings,'Audio model snapshot');
  if(kind==='image'&&!quants.length)quants=snapshotQuant(raw.siblings,'Pipeline snapshot');
  if(!quants.some(q=>q.recommended)&&quants[0])quants[0].recommended=true;
  const hasGguf=kind==='llm'&&quants.some(q=>q.file!=='*'&&/\.gguf$/i.test(q.file||''));
  const imageSnapshot=kind==='image'&&quants.some(q=>q.file==='*');
  const runtime=kind==='llm'?(hasGguf?'llama.cpp':'transformers-python'):kind==='image'?(imageSnapshot||hint==='diffusers'?'diffusers-python':'stable-diffusion.cpp'):'audio-python';
  return{id:`${source==='lmstudio'?'lms':'hf'}-${raw.id}`,name:raw.id.split('/').pop().replace(/-GGUF$/i,'').replace(/-/g,' '),publisher:raw.id.split('/')[0]||'Hugging Face',description:lmStudio.description||`${kind.toUpperCase()} · ${Number(raw.downloads||0).toLocaleString('en-US')} HF downloads`,kind,params:paramsFrom(raw.id,tags),context:contextFrom(raw),think,thinkLevels,vision,source,runtime,hfId:raw.id,lmStudioUrl:lmStudio.url,tags:tags.slice(0,40),quants,mmproj,license:raw.cardData?.license||raw.card_data?.license,downloads:raw.downloads||0,updatedAt:raw.lastModified,pipelineHint:kind==='image'?hint:undefined,runtimeSupported:true,downloadSupported:true,downloadOnly:false,gated:Boolean(raw.gated)};
}
async function fetchJson(url,{retryPublic=true}={}){const auth=await getHfAuthHeaders();let r=await fetch(url,{headers:{'user-agent':UA,accept:'application/json',...auth}});if(retryPublic&&(r.status===401||r.status===403)&&auth.authorization){r=await fetch(url,{headers:{'user-agent':UA,accept:'application/json'}});}if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);return r.json();}
async function fetchText(url){const r=await fetch(url,{headers:{'user-agent':UA,accept:'text/html'}});if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);return r.text();}
async function authState(){const auth=await getHfAuthHeaders();return Boolean(auth.authorization);}
export async function getHfModel(hfId,revision='main'){return fetchJson(`${HF_API}/${encodeURIComponent(hfId)}?blobs=true&revision=${encodeURIComponent(revision)}`);}
async function searchHfRaw(params,limit){const p=new URLSearchParams({...params,sort:'downloads',direction:'-1',limit:String(Math.max(1,Math.min(Number(limit||60),240))),full:'true'});if(!await authState())p.set('gated','false');return fetchJson(`${HF_API}?${p}`);}
async function searchHfOne({query='',kind='llm',limit=60}){const params={search:query};if(kind==='image')params.pipeline_tag='text-to-image';if(kind==='music')params.pipeline_tag='text-to-audio';const requestLimit=kind==='llm'?Math.min(240,Math.max(limit*2,limit)):limit;const rows=await searchHfRaw(params,requestLimit);return rows.map(r=>mapHf(r)).filter(Boolean).filter(m=>m.kind===kind).slice(0,limit);}
export async function searchHf({query='',kind='all',limit=60}){limit=Math.max(1,Math.min(Number(limit||60),240));if(kind!=='all')return searchHfOne({query,kind,limit});const settled=await Promise.allSettled(['llm','image','music'].map(k=>searchHfOne({query,kind:k,limit})));const merged=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);const seen=new Set();return merged.filter(m=>m&&!seen.has(m.id)&&(seen.add(m.id),true)).sort((a,b)=>Number(b.downloads||0)-Number(a.downloads||0)).slice(0,limit);}
function decodeHtml(s=''){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}function stripTags(s=''){return decodeHtml(s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());}
async function parseLmStudioDetail(url,depth=0){const html=await fetchText(url);const title=stripTags((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[,''])[1]).replace(/\s*[•|-]\s*LM Studio.*$/i,'');const desc=decodeHtml((html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']+)/i)||[,''])[1]);const text=stripTags(html);const repos=[...html.matchAll(/huggingface\.co\/([A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)/g)].map(m=>m[1]);const hfId=repos.find(r=>/gguf/i.test(r))||repos[0];if(!hfId&&depth<1){const nested=[...html.matchAll(/href=["'](\/models\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)["']/g)].map(m=>`https://lmstudio.ai${m[1]}`);const settled=await Promise.allSettled([...new Set(nested)].slice(0,12).map(u=>parseLmStudioDetail(u,depth+1)));return settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);}if(!hfId)return[];const think=/\bReasoning\b/i.test(text)||/Enable Thinking/i.test(text)||/reasoning effort/i.test(text);const thinkLevels=/reasoning effort[\s\S]{0,260}(low|medium|high)/i.test(text)||/configurable reasoning effort/i.test(text);const vision=/Vision Input|vision-language|multimodal/i.test(text);const raw=await getHfModel(hfId);const model=mapHf(raw,'lmstudio',{url,description:desc,think,thinkLevels,vision});if(model&&title)model.name=title;return model?[model]:[];}
export async function searchLmStudio({query='',limit=60,url=''}){if(url){const clean=String(url).startsWith('http')?String(url):`https://lmstudio.ai/models/${String(url).replace(/^\/+/, '')}`;return(await parseLmStudioDetail(clean)).slice(0,limit);}limit=Math.max(1,Math.min(Number(limit||60),240));const q=String(query||'').trim();const [community,compatible]=await Promise.allSettled([searchHfRaw({search:q,author:'lmstudio-community'},limit),searchHfRaw({search:q,apps:'llama.cpp'},limit)]);const raws=[...(community.status==='fulfilled'?community.value:[]),...(compatible.status==='fulfilled'?compatible.value:[])];const seen=new Set();return raws.map(r=>mapHf(r,'lmstudio',{description:'LM Studio / llama.cpp uyumlu model'})).filter(m=>m&&m.kind==='llm'&&!seen.has(m.hfId)&&(seen.add(m.hfId),true)).sort((a,b)=>Number(b.downloads||0)-Number(a.downloads||0)).slice(0,limit);}
export async function resolveModelSpec(spec){if(typeof spec==='object'&&spec?.hfId)return spec;const s=String(spec||'').trim();if(!s)throw new Error('Model kimliği gerekli.');if(s.includes('lmstudio.ai/models')){const rows=await searchLmStudio({url:s,limit:1});if(!rows[0])throw new Error('LM Studio model sayfası çözülemedi.');return rows[0];}const hf=s.replace(/^https?:\/\/huggingface\.co\//,'').split(/[?#]/)[0].replace(/\/(tree|resolve)\/.*$/,'');const raw=await getHfModel(hf);const mapped=mapHf(raw);if(!mapped)throw new Error('Model FlexLab tarafından çözülemedi.');return mapped;}
