import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { APP_HOME } from './config.mjs';
import { ensureStableDiffusionCpp } from './runtime-installer.mjs';
import { getInstalled } from './library.mjs';

export const IMAGE_OUTPUT_DIR=path.join(APP_HOME,'outputs','images');
const IMAGE_INPUT_DIR=path.join(APP_HOME,'inputs','images');
function clamp(v,min,max,d){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;}function clampInt(v,min,max,d){return Math.round(clamp(v,min,max,d));}
function safeName(ext='png'){return `${Date.now()}-${crypto.randomUUID().slice(0,8)}.${ext}`;}
function parseDataUrl(s){const m=String(s||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)throw new Error('Geçersiz data URL.');const mime=m[1].toLowerCase();const ext=mime.includes('jpeg')?'jpg':mime.includes('webp')?'webp':'png';return{ext,bytes:Buffer.from(m[2],'base64')};}
async function walk(dir){const out=[];const stack=[dir];while(stack.length){const d=stack.pop();for(const e of await fs.readdir(d,{withFileTypes:true}).catch(()=>[])){const p=path.join(d,e.name);if(e.isDirectory())stack.push(p);else out.push(p);}}return out;}
function pick(files,re){return files.find(f=>re.test(f.replaceAll('\\','/').toLowerCase()))||null;}
function checkpoint(files){return pick(files,/(?:diffusion_models|transformer|unet)\/.*\.(?:safetensors|gguf)$/)||pick(files,/(?!.*uncond)(?:flux|qwen.?image|mage.?flow|ideogram|sd3|z.?image).*\.(?:safetensors|gguf)$/);}
function pipelineArgs(model,files){const hint=model.pipelineHint||'sd';if(model.quant?.file!=='*'&&hint==='sd')return['-m',model.localPath];const diffusion=checkpoint(files);if(!diffusion)throw new Error(`${hint} snapshot içinde diffusion checkpoint bulunamadı.`);const vae=pick(files,/(?:^|\/)[^/]*(?:vae|_ae)[^/]*\.(?:safetensors|gguf|bin)$/)||pick(files,/vae\/.*\.(?:safetensors|gguf|bin)$/);const mmproj=pick(files,/mmproj.*\.gguf$/);const uncond=pick(files,/uncond.*\.(?:safetensors|gguf)$/);const qwen=pick(files,/(?:text_encoders|text_encoder).*qwen.*\.(?:gguf|safetensors)$/)||pick(files,/qwen.*(?:instruct|vl).*\.(?:gguf|safetensors)$/);const mistral=pick(files,/(?:text_encoders|text_encoder).*mistral.*\.(?:gguf|safetensors)$/);const t5=pick(files,/(?:text_encoders|text_encoder).*t5.*\.(?:gguf|safetensors|bin)$/)||pick(files,/(?:^|\/)t5[^/]*\.(?:gguf|safetensors|bin)$/);const clipL=pick(files,/(?:clip_l|clip-l).*\.(?:gguf|safetensors|bin)$/);const clipG=pick(files,/(?:clip_g|clip-g).*\.(?:gguf|safetensors|bin)$/);const args=['--diffusion-model',diffusion];if(vae)args.push('--vae',vae);if(hint==='qwen-image'||hint==='mage-flow'){if(!vae)throw new Error(`${hint} için VAE eksik.`);if(!qwen)throw new Error(`${hint} için Qwen VL encoder eksik.`);args.push('--llm',qwen);if(mmproj)args.push('--llm_vision',mmproj);}else if(hint==='flux2'){if(!vae)throw new Error('FLUX.2 VAE eksik.');const llm=mistral||qwen;if(!llm)throw new Error('FLUX.2 LLM encoder eksik.');args.push('--llm',llm);if(mmproj)args.push('--llm_vision',mmproj);}else if(hint==='ideogram4'){if(!vae||!qwen||!uncond)throw new Error('Ideogram4 companion dosyaları eksik.');args.push('--uncond-diffusion-model',uncond,'--llm',qwen);if(mmproj)args.push('--llm_vision',mmproj);}else if(hint==='sd3'){if(!t5||!clipL||!clipG)throw new Error('SD3/3.5 için clip_l, clip_g ve t5xxl eksik.');args.push('--t5xxl',t5,'--clip_l',clipL,'--clip_g',clipG);}else{if(t5)args.push('--t5xxl',t5);if(clipL)args.push('--clip_l',clipL);if(clipG)args.push('--clip_g',clipG);}return args;}
function run(exe,args){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';const add=c=>{log+=c.toString();};child.stdout?.on('data',add);child.stderr?.on('data',add);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error(`stable-diffusion.cpp ${code} ile kapandı.\n${log.slice(-6000)}`)));});}
export async function generateImageLocal(opts={}){const model=await getInstalled(opts.modelId);if(!model)throw new Error('Görüntü modeli kurulu değil.');if(model.kind!=='image')throw new Error('Seçilen model görüntü modeli değil.');const exe=await ensureStableDiffusionCpp();await fs.mkdir(IMAGE_OUTPUT_DIR,{recursive:true});await fs.mkdir(IMAGE_INPUT_DIR,{recursive:true});const outputName=safeName('png'),outputPath=path.join(IMAGE_OUTPUT_DIR,outputName),hint=model.pipelineHint||'sd',desc=`${model.name||''} ${model.hfId||''}`.toLowerCase();const defaultSteps=hint==='qwen-image'?20:hint==='mage-flow'&&/turbo/.test(desc)?4:hint==='mage-flow'?30:hint==='flux2'&&/klein/.test(desc)?4:24;const defaultCfg=hint==='qwen-image'?2.5:hint==='mage-flow'&&/turbo/.test(desc)?1:hint==='mage-flow'?4:hint==='flux2'?1:hint==='sd3'?4.5:7;const width=clampInt(opts.width,256,2048,1024),height=clampInt(opts.height,256,2048,1024),steps=clampInt(opts.steps,1,150,defaultSteps),cfg=clamp(opts.cfgScale,0,30,defaultCfg),seed=Number.isFinite(Number(opts.seed))?Math.trunc(Number(opts.seed)):-1;const files=(model.quant?.file==='*'||hint!=='sd')?await walk(model.localDir):[model.localPath];const args=[...pipelineArgs(model,files),'-p',String(opts.prompt||'').trim(),'-o',outputPath,'-W',String(width),'-H',String(height),'--steps',String(steps),'--cfg-scale',String(cfg),'--seed',String(seed),'--auto-fit'];if(opts.negativePrompt)args.push('-n',String(opts.negativePrompt));if(model.quant?.file==='*'||hint!=='sd')args.push('--diffusion-fa','--offload-to-cpu');if(hint==='qwen-image')args.push('--flow-shift','3');let inputPath=null;if(opts.imageDataUrl){const parsed=parseDataUrl(opts.imageDataUrl);inputPath=path.join(IMAGE_INPUT_DIR,safeName(parsed.ext));await fs.writeFile(inputPath,parsed.bytes);if(['qwen-image','mage-flow','flux2'].includes(hint))args.push('-r',inputPath);else args.push('-i',inputPath,'--strength',String(clamp(opts.strength,0,1,0.65)));}try{await run(exe,args);const st=await fs.stat(outputPath);if(!st.size)throw new Error('Boş görüntü çıktısı.');return{ok:true,file:outputName,url:`/api/outputs/images/${encodeURIComponent(outputName)}`,modelId:model.id,width,height,steps,seed,pipeline:hint};}finally{if(inputPath)await fs.rm(inputPath,{force:true}).catch(()=>{});}}
