import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { Readable } from 'node:stream';
import { PUBLIC_PORT, MCP_FILE, loadConfig, saveConfig, ensureDirs, createApiToken, revokeApiToken, verifyApiToken, publicConfig, writeJsonAtomic, readJson } from './config.mjs';
import { searchHf, searchLmStudio, resolveModelSpec } from './catalog.mjs';
import { loadLibrary, removeInstalled } from './library.mjs';
import { startDownload, getDownloadJob, listDownloadJobs } from './downloader.mjs';
import { ensureLoaded, loadModel, unloadModel, runtimeState, getInstance, instanceUrl, touchModel, modelEstimate } from './llama-manager.mjs';
import { webSearch, sourceContext } from './web-search.mjs';
import { ensureLlamaCpp, ensureStableDiffusionCpp, ensureMusicGenPython, runtimeInstallState } from './runtime-installer.mjs';
import { generateImageLocal, IMAGE_OUTPUT_DIR } from './image-manager.mjs';
import { generateMusicLocalNative, MUSIC_OUTPUT_DIR } from './music-manager.mjs';
import { hardwareInfo } from './hardware.mjs';
import { buildMcpToolset } from './mcp.mjs';

const MAX_BODY=128*1024*1024, MANAGEMENT_TOKEN=String(process.env.FLEXLAB_MANAGEMENT_TOKEN||'');
const chats=new Map();
function loopback(req){const a=String(req.socket?.remoteAddress||'');return a==='127.0.0.1'||a==='::1'||a.startsWith('::ffff:127.');}
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y);}
function internal(req){return loopback(req)&&MANAGEMENT_TOKEN&&safeEqual(req.headers['x-flexlab-management-token'],MANAGEMENT_TOKEN);}
function internalPreflight(req){return loopback(req)&&req.method==='OPTIONS'&&String(req.headers['access-control-request-headers']||'').toLowerCase().includes('x-flexlab-management-token');}
function cors(req,cfg,force=false){const origin=String(req.headers.origin||'');if(force)return{'access-control-allow-origin':origin||'*','vary':'Origin','access-control-allow-headers':'authorization,content-type,x-flexlab-management-token','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS'};if(!cfg?.corsEnabled)return{};const allowed=cfg.corsOrigins||[];if(allowed.includes('*'))return{'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'};if(origin&&allowed.some(x=>origin===x||origin.startsWith(`${x}:`)))return{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'};return{};}
function json(res,status,value,headers={}){const s=JSON.stringify(value);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(s),...headers});res.end(s);}
async function raw(req){let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>MAX_BODY)throw new Error('İstek çok büyük.');chunks.push(c);}return Buffer.concat(chunks);}
async function body(req){const b=await raw(req);return b.length?JSON.parse(b.toString('utf8')):{};}
async function form(req){const b=await raw(req);return new Request('http://flexlab.local/form',{method:'POST',headers:req.headers,body:b}).formData();}
function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');}
async function auth(req,scope='inference'){const cfg=await loadConfig();if(internal(req))return{ok:true,cfg,internal:true};if(!cfg.serverEnabled)return{ok:false,status:503,cfg,message:'FlexLab server kapalı.'};if(!cfg.authEnabled)return{ok:true,cfg};const ok=await verifyApiToken(bearer(req),scope);return{ok,status:ok?200:401,cfg,message:ok?'':'Geçerli FlexLab API token gerekli.'};}
function lastUser(messages=[]){const m=[...messages].reverse().find(x=>x.role==='user');if(!m)return'';if(typeof m.content==='string')return m.content;if(Array.isArray(m.content))return m.content.filter(x=>x?.type==='text'||x?.type==='input_text').map(x=>x.text||'').join('\n');return'';}
function stripWeb(messages=[]){return messages.map(m=>m.role!=='user'?m:{...m,content:typeof m.content==='string'?m.content.replace(/@Web\b/gi,'').trim():Array.isArray(m.content)?m.content.map(p=>p?.type==='text'?{...p,text:String(p.text||'').replace(/@Web\b/gi,'').trim()}:p):m.content});}
function addSystem(messages,ctx){if(!ctx)return messages;const c=structuredClone(messages||[]),i=c.findIndex(m=>m.role==='system');if(i>=0)c[i].content=`${c[i].content||''}\n\n${ctx}`.trim();else c.unshift({role:'system',content:ctx});return c;}
function safeOutput(root,name){const n=path.basename(String(name||''));if(!n||n!==String(name||''))return null;const f=path.resolve(root,n);return f.startsWith(path.resolve(root)+path.sep)?f:null;}
async function output(res,root,name,mime,headers={}){const f=safeOutput(root,decodeURIComponent(name));if(!f)return json(res,400,{error:{message:'Geçersiz çıktı yolu.'}},headers);try{const d=await fs.readFile(f);res.writeHead(200,{'content-type':mime,'content-length':d.length,'cache-control':'private, max-age=31536000',...headers});res.end(d);}catch{json(res,404,{error:{message:'Çıktı bulunamadı.'}},headers);}}
async function parseResponse(r){const t=await r.text();try{return JSON.parse(t);}catch{return{error:{message:t||`HTTP ${r.status}`}};}}
async function engineJson(modelId,endpoint,payload,loadOpts={}){await ensureLoaded(modelId,{jit:true,...loadOpts});touchModel(modelId,true);try{const r=await fetch(`${instanceUrl(modelId)}${endpoint}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await parseResponse(r);if(!r.ok)throw new Error(d?.error?.message||`llama.cpp HTTP ${r.status}`);return d;}finally{touchModel(modelId,false);}}
async function proxy(req,res,modelId,endpoint,payload,headers={}){await ensureLoaded(modelId,{jit:true,embedding:endpoint==='/v1/embeddings',reranking:endpoint==='/reranking',ttl:payload.ttl});touchModel(modelId,true);try{const r=await fetch(`${instanceUrl(modelId)}${endpoint}`,{method:req.method,headers:{'content-type':req.headers['content-type']||'application/json'},body:req.method==='GET'?undefined:JSON.stringify(payload)});res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json',...headers});if(r.body)Readable.fromWeb(r.body).pipe(res);else res.end();}finally{res.once('close',()=>touchModel(modelId,false));}}
function modelShape(m){const loaded=runtimeState().instances.filter(i=>i.id===m.id);return{type:m.embedding?'embedding':m.kind==='llm'?'llm':m.kind,publisher:m.publisher||'',key:m.id,display_name:m.name||m.id,architecture:m.metadata?.architecture||null,quantization:m.quant?{name:m.quant.label||null}:null,size_bytes:Number(m.quant?.sizeBytes||0),params_string:m.params||null,loaded_instances:loaded.map(i=>({id:i.instance_id,context_length:i.context})),flexlab:{vision:m.vision,reasoning:m.think,kind:m.kind,pipeline:m.pipelineHint}};}
function sse(res,event,data){res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);}
function inputContent(input){if(typeof input==='string')return input;if(!Array.isArray(input))return'';return input.map(x=>x.type==='message'?{type:'text',text:String(x.content||'')}:x.type==='image'&&x.data_url?{type:'image_url',image_url:{url:x.data_url}}:null).filter(Boolean);}
async function nativeChat(b){const lib=await loadLibrary(),m=lib.models.find(x=>x.id===b.model);if(!m||m.kind!=='llm')throw new Error('Geçerli kurulu LLM/VLM gerekli.');const old=b.previous_response_id?chats.get(b.previous_response_id):null;if(b.previous_response_id&&!old)throw new Error('previous_response_id bulunamadı.');let messages=old?structuredClone(old.messages):[];if(b.system_prompt&&!messages.some(x=>x.role==='system'))messages.unshift({role:'system',content:String(b.system_prompt)});messages.push({role:'user',content:inputContent(b.input)});const q=typeof b.input==='string'?b.input:lastUser(messages),sources=(b.web_search||/@Web\b/i.test(q))?await webSearch(q.replace(/@Web\b/gi,'').trim()):[];if(sources.length)messages=addSystem(stripWeb(messages),sourceContext(sources));const cfg=await loadConfig();const mcp=(cfg.mcpEnabled&&(b.integrations?.length||cfg.allowConfiguredMcp))?await buildMcpToolset(b.integrations||[],cfg.allowConfiguredMcp):null;const kwargs={};if(b.reasoning==='off'||b.reasoning==='on')kwargs.enable_thinking=b.reasoning==='on';if(['low','medium','high'].includes(b.reasoning)){kwargs.enable_thinking=true;kwargs.reasoning_effort=b.reasoning;}let final,usage={};try{for(let round=0;round<8;round++){const d=await engineJson(b.model,'/v1/chat/completions',{model:b.model,messages,stream:false,temperature:b.temperature,max_tokens:b.max_output_tokens,tools:mcp?.tools?.map(({_mcp,...x})=>x),tool_choice:mcp?.tools?.length?'auto':undefined,chat_template_kwargs:kwargs},{ttl:b.ttl,context_length:b.context_length});usage=d.usage||usage;const msg=d.choices?.[0]?.message||{};messages.push(msg);if(!msg.tool_calls?.length){final=msg;break;}for(const call of msg.tool_calls){const result=await mcp.execute(call);messages.push({role:'tool',tool_call_id:call.id,name:call.function?.name,content:JSON.stringify(result)});}}}finally{mcp?.close();}if(!final)throw new Error('MCP tool loop sınırına ulaştı.');const id=`resp_${crypto.randomUUID()}`;chats.set(id,{messages,at:Date.now()});if(chats.size>200){const oldest=[...chats.entries()].sort((a,b)=>a[1].at-b[1].at).slice(0,50);for(const [k] of oldest)chats.delete(k);}const out=[];if(final.reasoning_content)out.push({type:'reasoning',content:final.reasoning_content});out.push({type:'message',role:'assistant',content:final.content||''});return{response_id:id,model:b.model,output:out,usage,sources};}
await ensureDirs();
let boundHost=(await loadConfig()).host;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/','http://localhost'),cfg=await loadConfig(),ih=internal(req)||internalPreflight(req),ch=cors(req,cfg,ih);if(req.method==='OPTIONS'){res.writeHead(204,ch);return res.end();}if(u.pathname==='/health')return json(res,200,{ok:true,service:'flexlab-native',version:'0.4.0',runtime:runtimeState()},ch);
  // Loopback-only desktop management API
  if(u.pathname.startsWith('/api/')&&!u.pathname.startsWith('/api/v1/')&&!u.pathname.startsWith('/api/outputs/')){if(!internal(req))return json(res,403,{error:{message:'FlexLab management token gerekli.'}},cors(req,cfg,true));
    if(u.pathname==='/api/server'&&req.method==='GET')return json(res,200,{...publicConfig(cfg),runtime:runtimeState()},ch);
    if(u.pathname==='/api/server'&&['PATCH','POST'].includes(req.method)){const oldHost=cfg.host,n=await saveConfig(await body(req));if(oldHost!==n.host)setTimeout(()=>rebind(n.host),50);return json(res,200,publicConfig(n),ch);}
    if(u.pathname==='/api/server/tokens'&&req.method==='POST')return json(res,201,await createApiToken(await body(req)),ch);
    if(u.pathname.startsWith('/api/server/tokens/')&&req.method==='DELETE')return json(res,200,{ok:await revokeApiToken(decodeURIComponent(u.pathname.split('/').pop()))},ch);
    if(u.pathname==='/api/hardware'&&req.method==='GET')return json(res,200,await hardwareInfo(),ch);
    if(u.pathname==='/api/runtimes'&&req.method==='GET')return json(res,200,await runtimeInstallState(),ch);
    if(u.pathname.startsWith('/api/runtimes/')&&req.method==='POST'){const name=decodeURIComponent(u.pathname.split('/').pop());const p=name==='llama.cpp'?await ensureLlamaCpp():name==='stable-diffusion.cpp'?await ensureStableDiffusionCpp():name==='musicgen-python'?await ensureMusicGenPython():null;if(!p)throw new Error('Bilinmeyen runtime.');return json(res,200,{ok:true,path:p,state:await runtimeInstallState()},ch);}
    if(u.pathname==='/api/catalog'&&req.method==='GET'){const provider=u.searchParams.get('provider')||'huggingface',query=u.searchParams.get('q')||'',kind=u.searchParams.get('kind')||'all',limit=Number(u.searchParams.get('limit')||24);return json(res,200,{models:provider==='lmstudio'?await searchLmStudio({query,limit}):await searchHf({query,kind,limit})},ch);}
    if(u.pathname==='/api/models'&&req.method==='GET')return json(res,200,{...(await loadLibrary()),runtime:runtimeState(),downloads:listDownloadJobs()},ch);
    if(u.pathname==='/api/models/download'&&req.method==='POST'){const b=await body(req),model=b.model?.hfId?b.model:await resolveModelSpec(b.model||b.url),job=await startDownload(model,b.quantId||b.quantization,{revision:b.revision});return json(res,202,job,ch);}
    if(u.pathname.startsWith('/api/models/download/')&&req.method==='GET'){const j=getDownloadJob(decodeURIComponent(u.pathname.split('/').pop()));return j?json(res,200,j,ch):json(res,404,{error:{message:'Job bulunamadı.'}},ch);}
    if(u.pathname==='/api/models/load'&&req.method==='POST'){const b=await body(req);return json(res,200,await loadModel(b.id||b.model,b),ch);}
    if(u.pathname==='/api/models/unload'&&req.method==='POST'){const b=await body(req);return json(res,200,{ok:await unloadModel(b.id||b.model)},ch);}
    if(u.pathname==='/api/models/estimate'&&req.method==='POST'){const b=await body(req);return json(res,200,await modelEstimate(b.id||b.model,b),ch);}
    if(u.pathname.startsWith('/api/models/')&&req.method==='DELETE'){const id=decodeURIComponent(u.pathname.slice('/api/models/'.length));await unloadModel(id);return json(res,200,{ok:await removeInstalled(id)},ch);}
    if(u.pathname==='/api/mcp'&&req.method==='GET')return json(res,200,await readJson(MCP_FILE,{servers:[]}),ch);
    if(u.pathname==='/api/mcp'&&req.method==='POST'){const b=await body(req);await writeJsonAtomic(MCP_FILE,b);return json(res,200,b,ch);}
    if(u.pathname==='/api/web-search'&&req.method==='POST'){const b=await body(req);return json(res,200,{hits:await webSearch(b.query)},ch);}
    if(u.pathname==='/api/generate/image'&&req.method==='POST')return json(res,200,await generateImageLocal(await body(req)),ch);
    if(u.pathname==='/api/generate/music'&&req.method==='POST')return json(res,200,await generateMusicLocalNative(await body(req)),ch);
  }
  if(u.pathname.startsWith('/api/outputs/images/')&&req.method==='GET')return output(res,IMAGE_OUTPUT_DIR,u.pathname.slice('/api/outputs/images/'.length),'image/png',ch);
  if(u.pathname.startsWith('/api/outputs/music/')&&req.method==='GET')return output(res,MUSIC_OUTPUT_DIR,u.pathname.slice('/api/outputs/music/'.length),'audio/wav',ch);
  // LM Studio v1 compatibility
  if(u.pathname.startsWith('/api/v1/')){const a=await auth(req,u.pathname.includes('/models/')?'models':'inference');if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const h=cors(req,a.cfg);
    if(u.pathname==='/api/v1/models'&&req.method==='GET'){const lib=await loadLibrary();return json(res,200,{models:lib.models.map(modelShape)},h);}
    if(u.pathname==='/api/v1/models/load'&&req.method==='POST'){const b=await body(req),r=await loadModel(b.model,b);return json(res,200,{type:r.embedding?'embedding':'llm',instance_id:r.id,load_time_seconds:r.load_time_seconds,status:'loaded',load_config:r.load_config},h);}
    if(u.pathname==='/api/v1/models/unload'&&req.method==='POST'){const b=await body(req);return json(res,200,{status:'unloaded',ok:await unloadModel(b.instance_id||b.model)},h);}
    if(u.pathname==='/api/v1/models/download'&&req.method==='POST'){const b=await body(req),m=await resolveModelSpec(b.model||b.url),j=await startDownload(m,b.quantization,{revision:b.revision});return json(res,202,{job_id:j.id,status:j.status},h);}
    if(u.pathname==='/api/v1/models/download/status'&&req.method==='GET'){const j=getDownloadJob(u.searchParams.get('job_id')||u.searchParams.get('id'));return j?json(res,200,j,h):json(res,404,{error:{message:'Job bulunamadı.'}},h);}
    if(u.pathname==='/api/v1/chat'&&req.method==='POST'){const b=await body(req);if(!b.stream)return json(res,200,await nativeChat(b),h);res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache',...h});sse(res,'chat.start',{model:b.model});try{const r=await nativeChat(b);for(const x of r.output){const ev=x.type==='reasoning'?'reasoning.delta':'message.delta';sse(res,ev,{type:ev,content:x.content});}sse(res,'chat.end',r);}catch(e){sse(res,'error',{error:{message:e.message}});}return res.end();}
    return json(res,404,{error:{message:'Not found'}},h);
  }
  // Public OpenAI + Anthropic APIs
  if(u.pathname==='/v1/models'&&req.method==='GET'){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const lib=await loadLibrary();return json(res,200,{object:'list',data:lib.models.map(m=>({id:m.id,object:'model',created:Math.floor((m.installedAt||Date.now())/1000),owned_by:m.publisher||'local',flexlab:{kind:m.kind,vision:m.vision,reasoning:m.think,embedding:m.embedding,context:m.context}}))},cors(req,a.cfg));}
  if(u.pathname==='/v1/images/generations'&&req.method==='POST'){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const b=await body(req),o=await generateImageLocal({modelId:b.model,prompt:b.prompt,width:b.width,height:b.height,steps:b.steps,cfgScale:b.cfg_scale,seed:b.seed,negativePrompt:b.negative_prompt});const bytes=await fs.readFile(path.join(IMAGE_OUTPUT_DIR,o.file));return json(res,200,{created:Math.floor(Date.now()/1000),data:[{b64_json:bytes.toString('base64')}]},cors(req,a.cfg));}
  if(u.pathname==='/v1/images/edits'&&req.method==='POST'){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const f=await form(req),img=f.get('image');if(!(img instanceof Blob))throw new Error('image dosyası gerekli.');const dataUrl=`data:${img.type||'image/png'};base64,${Buffer.from(await img.arrayBuffer()).toString('base64')}`,o=await generateImageLocal({modelId:String(f.get('model')||''),prompt:String(f.get('prompt')||''),imageDataUrl:dataUrl,strength:Number(f.get('strength')||0.65),width:Number(f.get('width')||1024),height:Number(f.get('height')||1024)}),bytes=await fs.readFile(path.join(IMAGE_OUTPUT_DIR,o.file));return json(res,200,{created:Math.floor(Date.now()/1000),data:[{b64_json:bytes.toString('base64')}]},cors(req,a.cfg));}
  if(u.pathname==='/v1/audio/generations'&&req.method==='POST'){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const b=await body(req),o=await generateMusicLocalNative({modelId:b.model,prompt:b.prompt,maxNewTokens:b.max_new_tokens,guidanceScale:b.guidance_scale});return json(res,200,{created:Math.floor(Date.now()/1000),data:[{url:`http://127.0.0.1:${PUBLIC_PORT}${o.url}`}]},cors(req,a.cfg));}
  if((u.pathname==='/reranking'||u.pathname==='/rerank')&&req.method==='POST'){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));const b=await body(req),id=b.model||runtimeState().loadedModelId;if(!id)return json(res,400,{error:{message:'model gerekli'}},cors(req,a.cfg));await ensureLoaded(id,{jit:true,reranking:true,ttl:b.ttl});return proxy(req,res,id,'/reranking',b,cors(req,a.cfg));}
  if(u.pathname.startsWith('/v1/')&&['POST','GET'].includes(req.method)){const a=await auth(req);if(!a.ok)return json(res,a.status,{error:{message:a.message}},cors(req,a.cfg));let b=req.method==='POST'?await body(req):{},id=b.model||runtimeState().loadedModelId;if(!id)return json(res,400,{error:{message:'model gerekli'}},cors(req,a.cfg));if(u.pathname==='/v1/chat/completions'){const text=lastUser(b.messages),ext=b.flexlab||{};if(ext.web_search||/@Web\b/i.test(text)){const hits=await webSearch(text.replace(/@Web\b/gi,'').trim());b={...b,messages:addSystem(stripWeb(b.messages),sourceContext(hits))};}if(ext.think!==undefined||ext.think_level||b.reasoning_effort)b={...b,chat_template_kwargs:{...(b.chat_template_kwargs||{}),...(ext.think!==undefined?{enable_thinking:Boolean(ext.think)}:{}),...(ext.think_level||b.reasoning_effort?{reasoning_effort:ext.think_level||b.reasoning_effort}:{})}};}const endpoint=u.pathname==='/v1/messages'?'/v1/messages':u.pathname;return proxy(req,res,id,endpoint,b,cors(req,a.cfg));}
  return json(res,404,{error:{message:'Not found'}},ch);
}catch(e){console.error(e);const cfg=await loadConfig().catch(()=>null);return json(res,500,{error:{message:e instanceof Error?e.message:String(e)}},cors(req,cfg,internal(req)));}});
function rebind(host){try{server.close(()=>{boundHost=host;server.listen(PUBLIC_PORT,host,()=>console.log(`FlexLab daemon: http://${host}:${PUBLIC_PORT}`));});server.closeAllConnections?.();}catch(e){console.error('rebind failed',e);}}
server.listen(PUBLIC_PORT,boundHost,()=>console.log(`FlexLab daemon: http://${boundHost}:${PUBLIC_PORT}`));
process.on('SIGINT',async()=>{await unloadModel();server.close(()=>process.exit(0));});process.on('SIGTERM',async()=>{await unloadModel();server.close(()=>process.exit(0));});
