const UA='Mozilla/5.0 (compatible; FlexLab/0.4.0; local AI web search)';
function decode(s=''){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#\d+;/g,' ');}
function strip(html=''){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function terms(q){return[...new Set(String(q).toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(x=>x.length>2))];}
function scoreText(text,qterms){const s=String(text).toLowerCase();return qterms.reduce((n,t)=>n+(s.includes(t)?1:0),0)/Math.max(1,qterms.length);}
function cleanUrl(raw){try{const u=new URL(raw);for(const k of [...u.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(k))u.searchParams.delete(k);u.hash='';return u.toString();}catch{return raw;}}
async function ddg(q){const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{'user-agent':UA,accept:'text/html'}});if(!r.ok)return[];const html=await r.text(),hits=[];const re=/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<a[^>]*class="result__snippet"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&hits.length<10){let url=m[1];const u=url.match(/uddg=([^&]+)/);if(u)url=decodeURIComponent(u[1]);hits.push({title:strip(m[2]),url:cleanUrl(url),snippet:strip(m[3]),provider:'duckduckgo'});}return hits;}
async function wiki(q){const r=await fetch(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(q)}&format=json&srlimit=4`,{headers:{'user-agent':UA}});if(!r.ok)return[];const j=await r.json();return(j.query?.search||[]).map(x=>({title:x.title,url:`https://en.wikipedia.org/?curid=${x.pageid}`,snippet:strip(x.snippet),provider:'wikipedia'}));}
function meta(html,names){for(const n of names){const a=new RegExp(`<meta[^>]+(?:name|property)=["']${n}["'][^>]+content=["']([^"']+)["']`,'i').exec(html);if(a)return decode(a[1]);const b=new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["']${n}["']`,'i').exec(html);if(b)return decode(b[1]);}return'';}
function extractMain(html){const body=(html.match(/<article\b[\s\S]*?<\/article>/i)||html.match(/<main\b[\s\S]*?<\/main>/i)||html.match(/<body\b[\s\S]*?<\/body>/i)||[''])[0];const paras=[...body.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map(m=>strip(m[1])).filter(x=>x.length>50);return paras.join('\n').slice(0,7000);}
async function enrich(hit,qterms){try{const u=new URL(hit.url);if(!/^https?:$/.test(u.protocol))return hit;const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),6500);const r=await fetch(hit.url,{headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml'},redirect:'follow',signal:ctl.signal});clearTimeout(t);const ct=r.headers.get('content-type')||'';if(!r.ok||!ct.includes('text/html'))return hit;const html=(await r.text()).slice(0,1_500_000);const title=meta(html,['og:title','twitter:title'])||strip((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[,''])[1])||hit.title;const description=meta(html,['description','og:description','twitter:description']);const date=meta(html,['article:published_time','date','datePublished','parsely-pub-date']);const content=extractMain(html);const snippet=(description||content||hit.snippet).slice(0,1800);return{...hit,title,url:cleanUrl(r.url||hit.url),snippet,content:content.slice(0,5000),publishedAt:date||undefined,relevance:scoreText(`${title} ${snippet} ${content}`,qterms)};}catch{return hit;}}
export async function webSearch(q){const query=String(q||'').trim().slice(0,400);if(!query)return[];const qterms=terms(query);const settled=await Promise.allSettled([ddg(query),wiki(query)]);const base=[],seen=new Set();for(const s of settled)if(s.status==='fulfilled')for(const h of s.value){const key=cleanUrl(h.url);if(key&&!seen.has(key)){seen.add(key);base.push({...h,url:key});}}const enriched=await Promise.all(base.slice(0,10).map(h=>enrich(h,qterms)));return enriched.map((h,i)=>({...h,relevance:h.relevance??scoreText(`${h.title} ${h.snippet}`,qterms),rank:i+1})).sort((a,b)=>(b.relevance||0)-(a.relevance||0)||a.rank-b.rank).slice(0,8);}
export function sourceContext(hits){if(!hits.length)return'';return`Fresh web search evidence collected by FlexLab. Use only when relevant. Cite factual claims with [1], [2], etc. Do not invent citations.\n\n${hits.map((h,i)=>`[${i+1}] ${h.title}\nURL: ${h.url}${h.publishedAt?`\nPublished: ${h.publishedAt}`:''}\n${h.snippet}${h.content?`\nExtract: ${h.content.slice(0,2200)}`:''}`).join('\n\n')}`;}
